apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: twitter-clone
type: Opaque
stringData:  # <--- Используем stringData вместо data
  # Здесь пишем пароли открытым текстом для примера
  POSTGRES_USER: "skillbox"
  POSTGRES_PASSWORD: "skillbox_2026"
  SECRET_KEY: "super_secret_key_2026_do_not_share"
  