apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: twitter-clone
data:
  POSTGRES_DB: "twitter_clone_db"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:29092"
  REDIS_URL: "redis://redis-service:6379/0"
