apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: twitter-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: twitter-clone-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests: { memory: "64Mi", cpu: "50m" }
            limits: { memory: "128Mi", cpu: "100m" }
          # === ДОБАВЛЕНО: Монтируем диск в Nginx ===
          volumeMounts:
            - name: media-storage
              mountPath: /usr/share/nginx/html/media
              # Nginx будет раздавать файлы отсюда
      # ==========================================

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: twitter-clone
spec:
  selector: { app: frontend }
  ports: [{ port: 80, targetPort: 80 }]
