apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: twitter-clone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
