FROM nginx:alpine

# Просто копируем готовые файлы из папки frontend в папку Nginx
COPY frontend/ /usr/share/nginx/html/

# Копируем медиа файлы в правильную позицию для Nginx
COPY static/media/ /usr/share/nginx/html/media/

# Копируем конфигурацию Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
